version: '3.7'

services:
  massey_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./db-data:/var/lib/mysql
      - ./chives-db:/docker-entrypoint-initdb.d
    networks:
      helper-dev-net:
        aliases:
          - 'massey_db'
  massey_backend:
    build:
      context: chives-backend
      dockerfile: Dockerfile
    ports:
      - "10005:10005"
    restart: always
    depends_on: 
      - massey_db 
    networks:
      helper-dev-net:
        aliases:
          - 'massey_backend'
  gateway:
    container_name: gateway
    ports:
      - 80:80
    expose: 
      - 80
    build:
      context: './gateway'
      dockerfile: Dockerfile
    depends_on:
      - chives-front
      - massey_backend
      - massey_db
    links:
      - chives-front
      - massey_backend
      - massey_db
    networks:
      helper-dev-net:
        aliases:
          - 'gateway'
  chives-front:
    container_name: chives
    build:
      context: chives
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    networks:
      helper-dev-net:
        aliases:
           - 'chives-fe'
    environment:
      - NODE_ENV=development
volumes:
    db-data:
networks:
    helper-dev-net:
      driver: bridge

